name: Lint and Format with Ruff

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run Ruff Lint Check
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"  # or specify a version
          args: "check"      # run Ruff lint

      - name: Run Ruff Format Check
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "format --check"  # run Ruff format check
